# Generated by Django 6.0.7 on 2026-08-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='visibilty',
            new_name='visibility',
        ),
    ]
