# Generated by Django 6.0.7 on 2026-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('new_post', 'New Diary Post')], max_length=30),
        ),
    ]
